ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ com.thematch.server.ApplicationKt.module ]
    }
}

jwt {
    secret = "the-match-jwt-secret-change-in-production"
    issuer = "thematch"
    audience = "thematch-users"
    realm = "The Match"
}
