version: 2.1

jobs:
  build:
    working_directory: ~/code
    docker:
      - image: cimg/android:2024.01
    environment:
      JVM_OPTS: -Xmx3200m
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    steps:
      - checkout
      - restore_cache:
          key: gradle-{{ checksum "gradle/libs.versions.toml" }}-{{ checksum "shared/build.gradle.kts" }}
      - run:
          name: Download Dependencies
          command: ./gradlew dependencies
      - run:
          name: Build Shared Module
          command: ./gradlew :shared:build
      - run:
          name: Build Server
          command: ./gradlew :server:build
      - run:
          name: Build Android App
          command: ./gradlew :composeApp:assembleDebug
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "gradle/libs.versions.toml" }}-{{ checksum "shared/build.gradle.kts" }}
      - store_artifacts:
          path: composeApp/build/outputs/apk/debug
          destination: apks

workflows:
  build:
    jobs:
      - build
