version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
    - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
    - checkout
    - restore_cache:
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    #      - run:
    #         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
    #         command: sudo chmod +x ./gradlew
    - run:
        name: Download Dependencies
        command: ./gradlew androidDependencies
    - run:
        name: building file
        command: ./gradlew assembleDebug |  echo ${CIRCLE_ARTIFACTS}


    - save_cache:
        paths:
        - ~/.gradle
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

    - store_artifacts:
        path: app/build/outputs/apk/debug
        destination: apkss
    - run:
        name: Upload to Slack
        command: |
          curl -F file=@haha -F "initial_comment=success is here" -F channels=testlewis -H "Authorization: Bearer xoxp-69325341207-265644467143-467782762213-5a119d9261b5905e5256c701017b847f" https://slack.com/api/files.upload


        #    - store_test_results:
    #        path: app/build/test-results
    # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples
